### ISSUE TITLE
Warnings about Node 12 deprecation with GHA

### ISSUE THREAD

**Issue by jblack6-byu** [byu-oit/github-action-create-ecr-repo-if-missing#22]
When building with this action, we see:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: byu-oit/github-action-create-ecr-repo-if-missing@v1

**Comment by joshgubler** [comment]
Resolved with release v2.0.0.
